project:
  type: book

book:
  title: "PREGVAL Book"
  author: "Francisco Sanchez-Saez"
  date: "last-modified"
  chapters:
    - index.qmd
    - "01_SIP_QC.qmd"
    - "02_PCV_2009_2012_QC.qmd"
    - "02_PCV_2013_2017_QC.qmd"
    - "02_PCV_2018_2021_QC.qmd"
    - "03_CEX_QC.qmd"
    - "04_MBDS_QC.qmd"
    - "05_AED_QC.qmd"
    
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

