project:
  type: book

book:
  title: "PREGVAL Project"
  author: "Francisco Sanchez-Saez"
  date: "last-modified"
  chapters:
    - index.qmd
    - "01_Introduction.qmd"
    - "02_Results.qmd"
    - summary.qmd

    
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

